### ISSUE TITLE
`puma` argument not working with 5-year 2018-2022 ACS PUMS

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#555]
The 2022 PUMS uses the new 2020 PUMAs for the first time.  This will be an issue for the next few years, as the samples prior to 2022 use the 2010 PUMAs, but the samples 2022 and later use the 2020 PUMAs.  

Census doesn't reconcile this in the data; instead it marks unused PUMA definitions as `-0009`.  See here: 

![image](https://github.com/walkerke/tidycensus/assets/4872833/84bf2366-f7fa-4884-b843-cf5ef2f111ec)

For prior years, we just throw an error message when PUMAs are requested and don't attempt to deal with it.  See here:  https://github.com/walkerke/tidycensus/blob/master/R/pums.R#L99-L102

This feels unsatisfactory to me as this will impact everything through the 2021-2025 ACS 5-year (which will be released in 2027!).  

I'd like to think through how to handle this appropriately.  

For users: you can still pass a vector of PUMAs using `variables_filter` to either `PUMA10` or `PUMA20` in the new data.  Though it may make sense for you to pull first by state (which I know is a hefty download for TX / CA) then filter carefully within R.

**Comment by walkerke** [comment]
Handling with an error for now: https://github.com/walkerke/tidycensus/blob/master/R/pums.R#L99-L106.  Need to think through a better solution, though.

**Comment by sfmfb-mtitsworth** [comment]
Has Census released any guidance on this? Not reconciling the two is incredibly frustrating. We could create our own crosswalk based on spatial overlap, but that seems likely to lead to fairly inaccurate results.

**Comment by mtworth** [comment]
This is a bummer. I submitted a ticket to Census. Perhaps we can encourage others? This effectively makes microdata at the PUMA level useless for the next several years, as I understand it.

**Comment by walkerke** [comment]
Yeah - I'd like to come up with some sort of solution, though it seems like it'd be a novel one as I don't see PUMA reconciliation done by Census or by IPUMS.  We possibly could come up with a crosswalk between the two.  The tricky thing is that while this is easier for faster-growing areas (PUMAs are typically split into multiple new PUMAs) to go backwards from 2020 to 2010, it is harder for slower-growing areas where PUMAs are consolidated or re-organized (common in rural areas).

**Comment by mtworth** [comment]
How about using Geocorr? 

https://mcdc.missouri.edu/applications/geocorr2022.html

**Comment by mtworth** [comment]
@walkerke see Census guidance [here](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/2018_2022ACS_PUMS_User_Guide.pdf). Page 14, section F. 

I can try to take a stab at a PR in the next month if that's of interest.

**Comment by elisemarie1120** [comment]
Hey @walkerke.
I've noticed a problem when trying to simply to create a data frame of housing only variables when I include the VACS (vacancy) variable. When I add VACS, or even when I try to ONLY pull VACS, it throws an error:
Downloading: 2 MB     Error in `dplyr::mutate()`:
! Can't transform a data frame with duplicate names.
Run `rlang::last_trace()` to see where the error occurred.

When I'm trying to pull any other variable, either alone or in a combination up to 30 variables and I do NOT include VACS, it downloads just fine. But when I add VACS and even when I add return_vacant=true, it still won't run.
I'm wondering if this issue is one of many with the new PUMA geographies being used in 2022?
When I select year=2021, VACS works and gives me options b - 7.

Just flagging this. I am a pretty new user so I thought it was something I was doing, but after a day of investigation, I think the problem is with the new geographic designations.

**Comment by walkerke** [comment]
@elisemarie1120 This doesn't have anything to do with PUMA geographies I don't think; see #560 .  

Try re-installing from GitHub with `remotes::install_github("walkerke/tidycensus")` and see if your code now runs, I just pushed a couple fixes.

**Comment by kirstinhuiber-ac** [comment]
> Handling with an error for now: https://github.com/walkerke/tidycensus/blob/master/R/pums.R#L99-L106. Need to think through a better solution, though.

@walkerke, hello! I work for a county-level local health department, and because get_pums doesn't have a "county" argument, I have been filtering PUMS data using the "puma" argument (regardless of whether I map or summarize to a PUMA level).  And because a county is a smaller geography and we want to look at race subpopulations, we almost exclusively use the 5-year surveys.  So this issue is affecting us greatly; I worry that we won't be able to see 5-year data specific to our county more recent than 2017-2021 until 2026, which isn't ideal.

Is there a way you could add a "county" argument to "get_pums"?  Is there a geography nesting problem?  I would imagine that PUMAs are nested within county boundaries, but I don't know that.  Relying on filtering on the PUMA values when they are not consistent across the 5-year period for half of every decade delays us being able to access data (particularly around social determinants of health) that are important to us.

I appreciate any other advice you have to give as well!

**Comment by kirstinhuiber-ac** [comment]
I'm replying to @walkerke's January 26, 2024 message, and I'm the epidemiologist working for a county local health jurisdiction (but a populous one: larger than 16 states).

If we were to run the single years on their appropriate PUMA values (so PUMA10 2018-2021, PUMA20 on 2022, or similarly for 2019-2023 once it's released), do you have any advice on how to average across the five years?  For estimates, we could take the mean (I think?).  But what about the moe?

That might be the needed workaround, assuming that the Census doesn't release a PUMA value crosswalk: functions that allow us to consolidate single-year data into ad hoc 5-year data.  Otherwise we end up unable to report on our smaller county subpopulations who really want information about how they're doing.

**Comment by jvtcl** [comment]
I just noticed this morning that this problem seems to be addressed for the ACS 2023 5-Year Estimates. There is now a [single PUMA label](https://api.census.gov/data/2023/acs/acs5/pums/variables/PUMA.json) available in place of `PUMA10` and `PUMA20`. This was not the case last week. 

However, it looks like the mixed geography problem persists for ACS 2022 5Y: https://api.census.gov/data/2022/acs/acs5/pums/variables.html
